name: Java test
on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  java-test:
    uses: ./.github/workflows/java-test-reusable.yaml

  docker-ci:
    needs: java-test
    uses: ./.github/workflows/docker-ci-reusable.yaml
